# Generated by Django 4.1.5 on 2023-04-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reffun'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loc', models.CharField(max_length=100)),
                ('p', models.IntegerField(default=1)),
            ],
        ),
    ]
