# Generated by Django 4.1.5 on 2023-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_waste'),
    ]

    operations = [
        migrations.CreateModel(
            name='es',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(max_length=100)),
                ('ph', models.IntegerField(max_length=100)),
            ],
        ),
    ]
