# Generated by Django 4.1.5 on 2023-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_es'),
    ]

    operations = [
        migrations.AlterField(
            model_name='es',
            name='ph',
            field=models.IntegerField(),
        ),
    ]
